# Generated by Django 2.0.1 on 2018-03-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kirrurl',
            name='Active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='kirrurl',
            name='shorturl',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
